"""
P4M3 Controller — Pure gRPC Implementation
Algorithm 3: Machine Learning Detection Module

Flow:
  1. Connect to all switches via P4Runtime/gRPC
  2. Install L2 forwarding rules (MAC -> port)
  3. Enable digest on leaf1 and leaf3 (cpu_digest_t, receiver_id=1)
  4. Block on gRPC stream — switch pushes digest messages the instant SYN fires
  5. On WINDOW_SIZE packets from same MAC: classify with ensemble, block if attack
"""

import os, sys, time, pickle, threading, logging
import numpy as np

sys.path.insert(0, '/home/ayush/p4-tools/p4-utils')
from p4utils.utils.sswitch_p4runtime_API import SimpleSwitchP4RuntimeAPI
from p4utils.utils.helper import load_topo

logging.basicConfig(level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s', datefmt='%H:%M:%S')
log = logging.getLogger('P4M3')
log.propagate = False

MODELS_DIR  = os.path.join(os.path.dirname(__file__), '../ml/models')
WINDOW_SIZE = 27

# cpu_digest_t receiver_id — must match digest<cpu_digest_t>(1, ...) in P4
DIGEST_RECEIVER_ID = 1

# Compiled P4 files — generated by network.py at startup in the project root directory
_PROJECT_ROOT = os.path.join(os.path.dirname(__file__), '..')
P4RT_PATH = os.path.join(_PROJECT_ROOT, 'p4src', 'ddos_detector_p4rt.txt')
JSON_PATH  = os.path.join(_PROJECT_ROOT, 'p4src', 'ddos_detector.json')

# MACs must match Scapy scripts (attack1/2/3, good1/2/3) and network.py setIntfMac
HOST_MACS = {
    'h1a': '2a:ac:90:97:e9:78',
    'h1b': '96:29:cc:a3:3d:7f',
    'h1c': '7e:8d:d4:8f:0e:67',
    'h2':  'f2:44:a6:63:0a:48',
    'h3a': '36:67:4e:e1:ec:8a',
    'h3b': 'b2:7f:69:b5:af:21',
    'h3c': '92:5d:3d:47:c2:94',
}

# Port numbers match the port1=/port2= values set in network.py addLink calls
PORT_MAP = {
    'leaf1': {
        'h1a': 1, 'h1b': 2, 'h1c': 3,
        'h2': 4, 'h3a': 4, 'h3b': 4, 'h3c': 4,
    },
    'leaf2': {
        'h2': 1,
        'h1a': 2, 'h1b': 2, 'h1c': 2, 'h3a': 2, 'h3b': 2, 'h3c': 2,
    },
    'leaf3': {
        'h3a': 1, 'h3b': 2, 'h3c': 3,
        'h1a': 4, 'h1b': 4, 'h1c': 4, 'h2': 4,
    },
    'spine1': {
        'h1a': 1, 'h1b': 1, 'h1c': 1,
        'h2':  2,
        'h3a': 3, 'h3b': 3, 'h3c': 3,
    },
}


class EnsembleClassifier:
    def __init__(self, models_dir):
        self.models = {}
        self.scaler = None
        log.info(f"Loading ML models from {models_dir}/")
        for name, fname in [('knn', 'knn_model.pkl'), ('rf', 'rf_model.pkl'),
                             ('dt', 'dt_model.pkl'),  ('xgb', 'xgb_model.pkl'),
                             ('svm', 'svm_model.pkl')]:
            path = os.path.join(models_dir, fname)
            if os.path.exists(path):
                with open(path, 'rb') as f:
                    self.models[name] = pickle.load(f)
                log.info(f"  Loaded: {name}")
            else:
                log.warning(f"  Missing: {path}")
        scaler_path = os.path.join(models_dir, 'scaler.pkl')
        if os.path.exists(scaler_path):
            with open(scaler_path, 'rb') as f:
                self.scaler = pickle.load(f)
        log.info(f"Ensemble ready: {len(self.models)} models")

    def predict(self, pps, duration, count):
        # Multiplier (5000x) scales up simulation-speed PPS to match
        # CICDDoS2019 training distribution (millions of pps)
        pps_scaled = pps * 5000.0
        features = np.array([[pps_scaled]])
        if self.scaler:
            features = self.scaler.transform(features)
        votes = sum(1 for m in self.models.values() if m.predict(features)[0] == 1)
        total = len(self.models)
        return votes > (total / 2), votes, total


class FlowTable:
    def __init__(self):
        self._flows = {}
        self._lock  = threading.Lock()

    def update(self, src_mac):
        now = time.time()
        with self._lock:
            if src_mac not in self._flows:
                self._flows[src_mac] = {
                    'first_time': now, 'last_time': now,
                    'packet_count': 1, 'blocked': False, 'classified': False}
                return False, 0.0, 0.0, 1
            flow = self._flows[src_mac]
            if flow['blocked']:
                return False, 0.0, 0.0, flow['packet_count']
            flow['packet_count'] += 1
            flow['last_time'] = now
            count    = flow['packet_count']
            duration = now - flow['first_time']
            if count == WINDOW_SIZE and not flow['classified']:
                flow['classified'] = True
                pps = count / duration if duration > 0 else float('inf')
                return True, pps, duration, count
        return False, 0.0, 0.0, 0

    def mark_blocked(self, src_mac):
        with self._lock:
            if src_mac in self._flows:
                self._flows[src_mac]['blocked'] = True


class P4M3Controller:
    def __init__(self):
        self.ensemble   = EnsembleClassifier(MODELS_DIR)
        self.flow_table = FlowTable()
        self.switches   = {}
        self.stats      = {'received': 0, 'attacks': 0, 'benign': 0, 'blocked': 0}
        self._lock      = threading.Lock()

        self.topo = load_topo('topology.json')

        self._connect_switches()
        self._install_forwarding_rules()
        self._enable_digests()

    def _connect_switches(self):
        log.info("Connecting to switches via P4Runtime/gRPC...")
        for sw in self.topo.get_p4switches():
            device_id = self.topo.get_p4switch_id(sw)
            grpc_port = self.topo.get_grpc_port(sw)
            try:
                self.switches[sw] = SimpleSwitchP4RuntimeAPI(
                    device_id = device_id,
                    grpc_port = grpc_port,
                    p4rt_path = P4RT_PATH,
                    json_path = JSON_PATH,
                )
                log.info(f"  Connected: {sw} (device_id:{device_id} grpc:{grpc_port})")
            except Exception as e:
                log.error(f"  Failed to connect {sw}: {e}")

    def _enable_digests(self):
        """Enable cpu_digest_t digest on leaf1 and leaf3.
        BMv2 will batch and send digest messages over the gRPC stream
        whenever digest<cpu_digest_t>(1, {...}) fires in the P4 pipeline."""
        log.info("Enabling digests...")
        for sw in ('leaf1', 'leaf3'):
            api = self.switches.get(sw)
            if not api:
                continue
            try:
                api.digest_enable('cpu_digest_t')
                log.info(f"  {sw}: digest enabled (receiver_id={DIGEST_RECEIVER_ID})")
            except Exception as e:
                log.warning(f"  Digest enable {sw}: {e}")

    def _install_forwarding_rules(self):
        log.info("Installing L2 forwarding rules...")
        for sw_name, port_table in PORT_MAP.items():
            api = self.switches.get(sw_name)
            if not api:
                continue
            for host_name, out_port in port_table.items():
                mac = HOST_MACS.get(host_name)
                if not mac:
                    continue
                try:
                    api.table_add('MyIngress.l2_forward',
                                  'MyIngress.forward_packet',
                                  [mac], [str(out_port)])
                    log.info(f"  {sw_name}: {host_name} ({mac}) -> port {out_port}")
                except Exception as e:
                    if 'already exists' not in str(e).lower():
                        log.warning(f"  Rule failed {sw_name}->{host_name}: {e}")

    def _push_block_rule(self, src_mac):
        blocked_on = []
        for sw_name, api in self.switches.items():
            try:
                api.table_add('MyIngress.dangerous_table',
                              'MyIngress.drop_packet',
                              [src_mac], [])
                blocked_on.append(sw_name)
            except Exception as e:
                if 'already exists' not in str(e).lower():
                    log.warning(f"  Block rule failed {sw_name}: {e}")
        return blocked_on

    def on_packet_in(self, src_mac, pps, duration, count):
        is_attack, votes, total = self.ensemble.predict(pps, duration, count)
        log.info(f"Classification: MAC={src_mac} PPS={pps:.1f} "
                 f"Duration={duration:.3f}s Vote={votes}/{total}")
        if is_attack:
            log.warning("-" * 55)
            log.warning(f"ATTACK DETECTED: {src_mac}")
            log.warning(f"  PPS={pps:.1f}  Vote={votes}/{total}  -> BLOCKING on all switches")
            self._push_block_rule(src_mac)
            log.warning("-" * 55)
            self.flow_table.mark_blocked(src_mac)
            with self._lock:
                self.stats['attacks'] += 1
                self.stats['blocked'] += 1
        else:
            log.info(f"BENIGN: {src_mac} ({pps:.1f} pps) -> allowed")
            with self._lock:
                self.stats['benign'] += 1

    def _recv_digest(self, sw_name):
        """Block on the P4Runtime gRPC stream and process digest messages from one switch.

        The gRPC stream is always open. When the P4 pipeline calls digest<cpu_digest_t>(1, {...}),
        the switch pushes the message immediately — this thread unblocks and processes it.
        timeout=1 is a recovery heartbeat only, not a polling interval.

        cpu_digest_t struct field order (matches P4 digest<cpu_digest_t>(1, {...})):
          [0] ingress_port  bit<16>
          [1] reason        bit<16>   (always 1)
          [2] src_mac       bit<48>
          [3] dst_port      bit<16>
          [4] cms_count     bit<32>
        """
        api = self.switches.get(sw_name)
        if not api:
            log.error(f"Digest receiver: no API for {sw_name}")
            return

        log.info(f"Digest receiver ready on {sw_name} (blocking on gRPC stream)")
        while True:
            try:
                # Blocks until the switch pushes a digest — no wakeup interval.
                # ACK is sent automatically by the wrapper after each DigestList.
                digest_list = api.get_digest_list(timeout=1)
                if digest_list is None:
                    continue

                for digest_entry in digest_list.data:
                    members = digest_entry.struct.members

                    reason = int.from_bytes(members[1].bitstring, 'big')
                    if reason != 1:
                        continue

                    src_mac_bytes = members[2].bitstring
                    src_mac = ':'.join(f'{b:02x}' for b in src_mac_bytes)

                    with self._lock:
                        self.stats['received'] += 1

                    should_classify, pps, duration, count = \
                        self.flow_table.update(src_mac)
                    if should_classify:
                        self.on_packet_in(src_mac, pps, duration, count)

            except Exception as e:
                # Timeout (no digest in 1s) is normal — loop continues blocking
                if 'timeout' not in str(e).lower():
                    log.error(f"Digest stream error on {sw_name}: {e}")

    def start(self):
        # Start one gRPC digest-receiver thread per digest-enabled leaf switch
        for sw in ('leaf1', 'leaf3'):
            t = threading.Thread(target=self._recv_digest, args=(sw,), daemon=True)
            t.start()

        log.info("")
        log.info("=" * 55)
        log.info("P4M3 Controller RUNNING (pure gRPC digest mode)")
        log.info(f"Window size : {WINDOW_SIZE} packets before classification")
        log.info(f"PPS multiplier: 5000x (scales sim speed to training data)")
        log.info("Attack (inter=0.01s) ~100pps  -> classified ATTACK -> BLOCKED")
        log.info("Benign (inter=0.5s)  ~2pps    -> classified BENIGN -> allowed")
        log.info("=" * 55)

        try:
            while True:
                time.sleep(10)
                with self._lock:
                    s = self.stats.copy()
                log.info(f"STATS | Received:{s['received']}  "
                         f"Attacks:{s['attacks']}  Benign:{s['benign']}  "
                         f"Blocked:{s['blocked']}")
        except KeyboardInterrupt:
            with self._lock:
                s = self.stats.copy()
            print("\n" + "=" * 55)
            print("FINAL STATS")
            print(f"  Packets received by controller : {s['received']}")
            print(f"  Attacks detected               : {s['attacks']}")
            print(f"  Benign flows                   : {s['benign']}")
            print(f"  MACs blocked                   : {s['blocked']}")
            print("=" * 55)


if __name__ == '__main__':
    ctrl = P4M3Controller()
    ctrl.start()
